To demonstrate the ``SequenceFeature().get_df_pos()`` method, we load the ``DOM_GSEC`` example dataset including its respective features  (see [Breimann24c]_):

In [7]:
import aaanalysis as aa
aa.options["verbose"] = False
df_seq = aa.load_dataset(name="DOM_GSEC", n=20)
labels = df_seq["label"].to_list()
df_feat = aa.load_features(name="DOM_GSEC").head(100)
features = df_feat["feature"].to_list()
sf = aa.SequenceFeature()
df_parts = sf.get_df_parts(df_seq=df_seq)
df_feat = sf.get_df_feat(features=features, labels=labels, df_parts=df_parts)
aa.display_df(df_feat, n_rows=5)

``df_feat`` must be provided to create ``df_pos``, containing an aggregated numerical value (``mean_dif`` column by default) per a selected scale category level (``category`` by default):

In [8]:
df_pos = sf.get_df_pos(df_feat=df_feat)
aa.display_df(df_feat, n_rows=5)

You can change the considered numerical and categorical columns using the ``col_value`` and ``col_cat`` parameters:

In [9]:
df_pos = sf.get_df_pos(df_feat=df_feat, col_value="abs_auc", col_cat="subcategory")
aa.display_df(df_feat, n_rows=5)

The residue positions can be adjusted using the ``start``, ``tmd_len``, ``jmd_n_len``, and ``jmd_c_len`` parameters:

In [10]:
# Shift positions by 10 residues
df_pos = sf.get_df_pos(df_feat=df_feat, start=11)
aa.display_df(df_feat, n_rows=5)

In [11]:
# Increase TMD length from 20 to 50
df_pos = sf.get_df_pos(df_feat=df_feat, tmd_len=50)
aa.display_df(df_feat, n_rows=5)

You can select a specific parts and normalize results using the ``list_parts`` and ``normalize`` parameters:

In [12]:
df_pos = sf.get_df_pos(df_feat=df_feat, list_parts=["jmd_c"], normalize=True)
aa.display_df(df_feat, n_rows=5)